using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using TestGenerator.Tests.Files;

namespace TestGenerator.Tests.Files.Tests
{
    public class MyClassTests
    {
        private MyClass _myClass;
        
        [SetUp]
        public void SetUp()
        {
            _myClass = new MyClass();
        }
        
        [Test]
        public void PublicVoidMethod1Test()
        {
            
            _myClass.PublicVoidMethod1();
            
            Assert.Fail("autogenerated");
        }
        
        [Test]
        public void PublicVoidMethod2Test()
        {
            decimal d = 0;
            OperatingSystem os = null;
            
            _myClass.PublicVoidMethod2(d, os);
            
            Assert.Fail("autogenerated");
        }
        
    }
}
